### ISSUE TITLE
Cannot create projects with official image

### ISSUE THREAD

**Issue by ey3ball** [scaleway/image-app-gitlab#1]
I've started the official gitlab image on a scalesway instance and have bumped into a major issue : it is not possible to create a new project using this image.

Error log:
```
Started GET "/projects/new" for xx.xx.xx.xx at 2015-08-06 15:24:22 +0000
Processing by ProjectsController#new as HTML
Completed 500 Internal Server Error in 159ms (ActiveRecord: 8.0ms)

ActionView::Template::Error ():
  (execjs):1
  execjs (2.5.2) lib/execjs/external_runtime.rb:214:in `exec_runtime'
  execjs (2.5.2) lib/execjs/external_runtime.rb:39:in `exec'
  execjs (2.5.2) lib/execjs/external_runtime.rb:14:in `initialize'
  execjs (2.5.2) lib/execjs/runtime.rb:44:in `new'
  execjs (2.5.2) lib/execjs/runtime.rb:44:in `compile'
  execjs (2.5.2) lib/execjs/module.rb:27:in `compile'
  coffee-script (2.4.1) lib/coffee_script.rb:50:in `context'
  coffee-script (2.4.1) lib/coffee_script.rb:78:in `compile'
  tilt (1.4.1) lib/tilt/coffee.rb:46:in `evaluate'
  tilt (1.4.1) lib/tilt/template.rb:103:in `render'
  (eval):5:in `render_with_options'
```

There is an upstream bug here with a similar error :

https://gitlab.com/gitlab-org/gitlab-ce/issues/1861

However the proposed workaround (`sudo apt-get install nodejs-legacy`) has no effect

It's nonetheless interesting, because :
```
root@scw-29fffc:~# /opt/gitlab/embedded/bin/node
Segmentation fault
```

Then if we do :
```
root@scw-29fffc:~# mv /opt/gitlab/embedded/bin/node /opt/gitlab/embedded/bin/node-old
root@scw-29fffc:~# ln -s /usr/bin/node /opt/gitlab/embedded/bin/node
```

Success !

```
Started GET "/projects/new" for xx.xx.xx.xx at 2015-08-06 15:28:17 +0000
Processing by ProjectsController#new as HTML
Completed 200 OK in 1744ms (Views: 1662.8ms | ActiveRecord: 28.6ms)
```

**Comment by moul** [comment]
Hi @ey3ball, thank you for reporting this issue, we will investigate

**Comment by edouardb** [comment]
Issue is fixed in Gitlab 7.13.3.
I tried it everything is fine, I created a new project successfully!

**Comment by moul** [comment]
New image deployed with ID 7ed176bf-918b-4962-9556-11140b46ad2b

You can run `scw run 7ed176bf-918b-4962-9556-11140b46ad2b` for testing

**Comment by QuentinPerez** [comment]
Hi,

I just tested with your image @moul, and It works

**Comment by edouardb** [comment]
Awesome!
